# Generated by Django 2.1.5 on 2020-01-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='작가 이름')),
                ('native', models.CharField(max_length=50, verbose_name='작가 출신')),
                ('birth_year', models.CharField(max_length=30, verbose_name='태어난 년도')),
                ('introduce', models.TextField(verbose_name='작가 소개')),
                ('belong', models.TextField(blank=True, verbose_name='소속 및 단체')),
                ('education', models.TextField(blank=True, verbose_name='학력 정보')),
                ('award', models.TextField(blank=True, verbose_name='수상 경력')),
                ('collection', models.TextField(blank=True, verbose_name='작품 소장처')),
                ('exhibition_history', models.TextField(blank=True, verbose_name='전시 경력')),
                ('like', models.PositiveSmallIntegerField(default=0, verbose_name='좋아요')),
                ('tag', models.CharField(blank=True, max_length=200, verbose_name='태그')),
                ('image', models.ImageField(upload_to='artist/%Y/%m/%d/', verbose_name='작가 이미지')),
            ],
            options={
                'verbose_name': '작가',
                'verbose_name_plural': '작가',
            },
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='전시명')),
                ('place', models.CharField(max_length=100, verbose_name='장소')),
                ('date_start', models.DateField(verbose_name='시작일')),
                ('date_end', models.DateField(verbose_name='종료일')),
                ('image_1', models.ImageField(upload_to='exhibition/%Y/%m/%d/', verbose_name='전시 이미지 1')),
            ],
            options={
                'verbose_name': '전시',
                'verbose_name_plural': '전시',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='갤러리 이름')),
                ('place', models.CharField(max_length=100, verbose_name='장소')),
                ('introduce', models.TextField(verbose_name='갤러리 소개')),
                ('like', models.PositiveSmallIntegerField(default=0, verbose_name='좋아요')),
                ('image_1', models.ImageField(upload_to='gallery/%Y/%m/%d/', verbose_name='갤러리 이미지 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/', verbose_name='갤러리 이미지 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='gallery/%Y/%m/%d/', verbose_name='갤러리 이미지 3')),
            ],
            options={
                'verbose_name': '갤러리',
                'verbose_name_plural': '갤러리',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='작품명')),
                ('price', models.CharField(max_length=100, verbose_name='가격')),
                ('material', models.CharField(max_length=100, verbose_name='재료')),
                ('size_horizontal', models.PositiveSmallIntegerField(default=0, verbose_name='사이즈 가로')),
                ('size_vertical', models.PositiveSmallIntegerField(default=0, verbose_name='사이즈 세로')),
                ('introduce', models.TextField(verbose_name='작품 소개')),
                ('recommend_reason', models.TextField(blank=True, verbose_name='추천 이유')),
                ('is_sale', models.BooleanField(default=False, verbose_name='판매 완료')),
                ('like', models.PositiveSmallIntegerField(default=0, verbose_name='좋아요')),
                ('image_1', models.ImageField(upload_to='picture/%Y/%m/%d/', verbose_name='작품 이미지 1')),
                ('image_2', models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d/', verbose_name='작품 이미지 2')),
                ('image_3', models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d/', verbose_name='작품 이미지 3')),
                ('image_4', models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d/', verbose_name='작품 이미지 4')),
                ('image_5', models.ImageField(blank=True, null=True, upload_to='picture/%Y/%m/%d/', verbose_name='작품 이미지 5')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artist_picture', to='art.Artist')),
                ('gallery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_picture', to='art.Gallery')),
            ],
            options={
                'verbose_name': '작품',
                'verbose_name_plural': '작품',
            },
        ),
        migrations.AddField(
            model_name='exhibition',
            name='gallery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_exhibition', to='art.Gallery'),
        ),
    ]
