# Generated by Django 2.1.5 on 2020-02-02 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='size_horizontal',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='사이즈 가로(cm)'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='size_vertical',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='사이즈 세로(cm)'),
        ),
    ]
