# Generated by Django 2.1.5 on 2020-02-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_auto_20200202_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='is_end',
            field=models.BooleanField(default=False, verbose_name='종료'),
        ),
    ]
