# Generated by Django 2.1.5 on 2020-03-22 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20200225_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='education',
        ),
        migrations.AddField(
            model_name='picture',
            name='buy_process',
            field=models.CharField(choices=[('입찰 중', '입찰 중'), ('판매 중', '판매 중'), ('작품 구매 문의', '작품 구매 문의')], default='판매 중', max_length=20, verbose_name='구매 방식'),
        ),
        migrations.AddField(
            model_name='picture',
            name='shipping_fee',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='배송비'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='award',
            field=models.TextField(blank=True, verbose_name='이력'),
        ),
    ]
