# Generated by Django 2.1.5 on 2020-03-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20200322_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='kind',
            field=models.CharField(choices=[('회화', '회화'), ('추상화', '추상화'), ('프린팅', '프린팅'), ('드로잉', '드로잉'), ('사진', '사진'), ('조긱품', '조각품')], default='회화', max_length=100, verbose_name='종류(유형)'),
        ),
    ]
