# Generated by Django 2.1.5 on 2020-08-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_exhibition_redirect_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_popular',
            field=models.BooleanField(default=False, verbose_name='인기있는작가'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.CharField(blank=True, max_length=30, verbose_name='태어난 년도'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='native',
            field=models.CharField(blank=True, max_length=50, verbose_name='작가 출신'),
        ),
    ]
