# Generated by Django 2.1.5 on 2020-08-10 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0009_auto_20200810_0128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=30)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist_tag', to='art.Artist')),
            ],
            options={
                'verbose_name': '작가 태그',
                'verbose_name_plural': '작가 태그',
            },
        ),
    ]
