# Generated by Django 2.1.5 on 2020-08-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0010_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='tag',
        ),
    ]
