# Generated by Django 2.1.5 on 2020-09-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_remove_artist_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='place',
            field=models.TextField(verbose_name='장소'),
        ),
    ]
