# Generated by Django 2.1.5 on 2020-08-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bannergallery_bannerhome'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannergallery',
            name='redirect_url',
            field=models.URLField(default='', verbose_name='클릭시 이동'),
        ),
    ]
